-- Every existing agency gets the permission template.
--
-- The tuples below are a SNAPSHOT of the catalogue as it stood when this
-- migration was written, deliberately frozen rather than re-derived from the
-- code at run time. A migration is a record of what actually happened to a
-- database; one that re-read today's catalogue would rewrite history every time
-- somebody added a module, and two agencies migrated a month apart would have
-- silently different pasts.
--
-- 168 rows per organization: one per role, per module, per action.
--
-- Transcribed from what the services did BEFORE any of this existed, so an
-- agency upgrades into the product it already had. Nothing reads these rows
-- yet -- enforcement moves across in the steps after this one -- so applying
-- this changes no behaviour at all, which is exactly what the two permission
-- matrices are checked against.

INSERT INTO "role_permissions"
    ("id", "organization_id", "role", "module", "action", "scope", "created_at", "updated_at")
SELECT
    gen_random_uuid()::text,
    o."id",
    seed."role"::"Role",
    seed."module",
    seed."action",
    seed."scope",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM "organizations" o
CROSS JOIN (
    VALUES
        ('admin', 'clients', 'view', 'all'),
        ('admin', 'clients', 'create', 'all'),
        ('admin', 'clients', 'edit', 'all'),
        ('admin', 'clients', 'delete', 'all'),
        ('admin', 'services', 'view', 'all'),
        ('admin', 'services', 'create', 'all'),
        ('admin', 'services', 'edit', 'all'),
        ('admin', 'services', 'delete', 'all'),
        ('admin', 'projects', 'view', 'all'),
        ('admin', 'projects', 'create', 'all'),
        ('admin', 'projects', 'edit', 'all'),
        ('admin', 'projects', 'delete', 'all'),
        ('admin', 'projects', 'assign', 'all'),
        ('admin', 'tasks', 'view', 'all'),
        ('admin', 'tasks', 'create', 'all'),
        ('admin', 'tasks', 'edit', 'all'),
        ('admin', 'tasks', 'delete', 'all'),
        ('admin', 'tasks', 'assign', 'all'),
        ('admin', 'team', 'view', 'all'),
        ('admin', 'team', 'create', 'all'),
        ('admin', 'team', 'edit', 'all'),
        ('admin', 'team', 'delete', 'all'),
        ('admin', 'chat', 'view', 'own'),
        ('admin', 'chat', 'create', 'own'),
        ('admin', 'accounts', 'view', 'all'),
        ('admin', 'accounts', 'create', 'all'),
        ('admin', 'accounts', 'edit', 'all'),
        ('admin', 'accounts', 'delete', 'all'),
        ('admin', 'reports', 'view', 'all'),
        ('admin', 'vault', 'view', 'all'),
        ('admin', 'vault', 'create', 'all'),
        ('admin', 'vault', 'edit', 'all'),
        ('admin', 'vault', 'delete', 'all'),
        ('admin', 'attendance', 'view', 'all'),
        ('admin', 'attendance', 'create', 'all'),
        ('admin', 'attendance', 'edit', 'all'),
        ('admin', 'leave', 'view', 'all'),
        ('admin', 'leave', 'create', 'all'),
        ('admin', 'leave', 'edit', 'all'),
        ('admin', 'time', 'view', 'all'),
        ('admin', 'time', 'create', 'all'),
        ('admin', 'time', 'edit', 'all'),
        ('sales', 'clients', 'view', 'all'),
        ('sales', 'clients', 'create', 'all'),
        ('sales', 'clients', 'edit', 'all'),
        ('sales', 'clients', 'delete', 'none'),
        ('sales', 'services', 'view', 'all'),
        ('sales', 'services', 'create', 'all'),
        ('sales', 'services', 'edit', 'all'),
        ('sales', 'services', 'delete', 'none'),
        ('sales', 'projects', 'view', 'all'),
        ('sales', 'projects', 'create', 'all'),
        ('sales', 'projects', 'edit', 'none'),
        ('sales', 'projects', 'delete', 'none'),
        ('sales', 'projects', 'assign', 'none'),
        ('sales', 'tasks', 'view', 'all'),
        ('sales', 'tasks', 'create', 'none'),
        ('sales', 'tasks', 'edit', 'own'),
        ('sales', 'tasks', 'delete', 'none'),
        ('sales', 'tasks', 'assign', 'none'),
        ('sales', 'team', 'view', 'all'),
        ('sales', 'team', 'create', 'none'),
        ('sales', 'team', 'edit', 'none'),
        ('sales', 'team', 'delete', 'none'),
        ('sales', 'chat', 'view', 'own'),
        ('sales', 'chat', 'create', 'own'),
        ('sales', 'accounts', 'view', 'none'),
        ('sales', 'accounts', 'create', 'none'),
        ('sales', 'accounts', 'edit', 'none'),
        ('sales', 'accounts', 'delete', 'none'),
        ('sales', 'reports', 'view', 'own'),
        ('sales', 'vault', 'view', 'all'),
        ('sales', 'vault', 'create', 'all'),
        ('sales', 'vault', 'edit', 'all'),
        ('sales', 'vault', 'delete', 'none'),
        ('sales', 'attendance', 'view', 'own'),
        ('sales', 'attendance', 'create', 'own'),
        ('sales', 'attendance', 'edit', 'none'),
        ('sales', 'leave', 'view', 'own'),
        ('sales', 'leave', 'create', 'own'),
        ('sales', 'leave', 'edit', 'none'),
        ('sales', 'time', 'view', 'own'),
        ('sales', 'time', 'create', 'own'),
        ('sales', 'time', 'edit', 'own'),
        ('project_manager', 'clients', 'view', 'all'),
        ('project_manager', 'clients', 'create', 'none'),
        ('project_manager', 'clients', 'edit', 'none'),
        ('project_manager', 'clients', 'delete', 'none'),
        ('project_manager', 'services', 'view', 'all'),
        ('project_manager', 'services', 'create', 'none'),
        ('project_manager', 'services', 'edit', 'none'),
        ('project_manager', 'services', 'delete', 'none'),
        ('project_manager', 'projects', 'view', 'all'),
        ('project_manager', 'projects', 'create', 'all'),
        ('project_manager', 'projects', 'edit', 'all'),
        ('project_manager', 'projects', 'delete', 'none'),
        ('project_manager', 'projects', 'assign', 'all'),
        ('project_manager', 'tasks', 'view', 'all'),
        ('project_manager', 'tasks', 'create', 'all'),
        ('project_manager', 'tasks', 'edit', 'all'),
        ('project_manager', 'tasks', 'delete', 'all'),
        ('project_manager', 'tasks', 'assign', 'all'),
        ('project_manager', 'team', 'view', 'all'),
        ('project_manager', 'team', 'create', 'none'),
        ('project_manager', 'team', 'edit', 'none'),
        ('project_manager', 'team', 'delete', 'none'),
        ('project_manager', 'chat', 'view', 'own'),
        ('project_manager', 'chat', 'create', 'own'),
        ('project_manager', 'accounts', 'view', 'none'),
        ('project_manager', 'accounts', 'create', 'none'),
        ('project_manager', 'accounts', 'edit', 'none'),
        ('project_manager', 'accounts', 'delete', 'none'),
        ('project_manager', 'reports', 'view', 'all'),
        ('project_manager', 'vault', 'view', 'all'),
        ('project_manager', 'vault', 'create', 'all'),
        ('project_manager', 'vault', 'edit', 'all'),
        ('project_manager', 'vault', 'delete', 'none'),
        ('project_manager', 'attendance', 'view', 'all'),
        ('project_manager', 'attendance', 'create', 'all'),
        ('project_manager', 'attendance', 'edit', 'all'),
        ('project_manager', 'leave', 'view', 'all'),
        ('project_manager', 'leave', 'create', 'own'),
        ('project_manager', 'leave', 'edit', 'all'),
        ('project_manager', 'time', 'view', 'all'),
        ('project_manager', 'time', 'create', 'own'),
        ('project_manager', 'time', 'edit', 'all'),
        ('operations', 'clients', 'view', 'assigned'),
        ('operations', 'clients', 'create', 'none'),
        ('operations', 'clients', 'edit', 'none'),
        ('operations', 'clients', 'delete', 'none'),
        ('operations', 'services', 'view', 'all'),
        ('operations', 'services', 'create', 'none'),
        ('operations', 'services', 'edit', 'none'),
        ('operations', 'services', 'delete', 'none'),
        ('operations', 'projects', 'view', 'assigned'),
        ('operations', 'projects', 'create', 'none'),
        ('operations', 'projects', 'edit', 'none'),
        ('operations', 'projects', 'delete', 'none'),
        ('operations', 'projects', 'assign', 'none'),
        ('operations', 'tasks', 'view', 'own'),
        ('operations', 'tasks', 'create', 'none'),
        ('operations', 'tasks', 'edit', 'own'),
        ('operations', 'tasks', 'delete', 'none'),
        ('operations', 'tasks', 'assign', 'none'),
        ('operations', 'team', 'view', 'all'),
        ('operations', 'team', 'create', 'none'),
        ('operations', 'team', 'edit', 'none'),
        ('operations', 'team', 'delete', 'none'),
        ('operations', 'chat', 'view', 'own'),
        ('operations', 'chat', 'create', 'own'),
        ('operations', 'accounts', 'view', 'none'),
        ('operations', 'accounts', 'create', 'none'),
        ('operations', 'accounts', 'edit', 'none'),
        ('operations', 'accounts', 'delete', 'none'),
        ('operations', 'reports', 'view', 'none'),
        ('operations', 'vault', 'view', 'assigned'),
        ('operations', 'vault', 'create', 'none'),
        ('operations', 'vault', 'edit', 'none'),
        ('operations', 'vault', 'delete', 'none'),
        ('operations', 'attendance', 'view', 'own'),
        ('operations', 'attendance', 'create', 'own'),
        ('operations', 'attendance', 'edit', 'none'),
        ('operations', 'leave', 'view', 'own'),
        ('operations', 'leave', 'create', 'own'),
        ('operations', 'leave', 'edit', 'none'),
        ('operations', 'time', 'view', 'own'),
        ('operations', 'time', 'create', 'own'),
        ('operations', 'time', 'edit', 'own')
) AS seed("role", "module", "action", "scope")
-- Re-runnable, and safe for an agency created between deploy and migration: the
-- unique index would refuse a duplicate anyway, and this says so out loud.
ON CONFLICT ("organization_id", "role", "module", "action") DO NOTHING;
